user nginx;
worker_processes 1;

events { 
        worker_connections 1024; # ccoonexiones  simultaneas por proceso
}

http {
    include mime.types; #diccionario que dice que .css es estilo y .jpg imagen
    default_type application/octet-stream; #si no conoce tipo, tratalo como binario

    server {
        listen 443 ssl; #puerto a escuchar y ssl ativa cifrado
        server_name dfernan3.42.fr localhost;

        ssl_protocols TLSv1.2 TLSv1.3; #permite acceso a esos protocolos seguros solo
        ssl_certificate /etc/ssl/certs/server.crt; #ruta cerficiado publico
        ssl_certificate_key /etc/ssl/private/server.key; #rita key

        root /var/www/wordpress; #donde estan fisicamente los archivos de tu web
        index index.php index.html; #archivos que nginx busca primero al entrar en carpeta

        location / { 
            try_files $uri $uri/ /index.php?$args; #busca archivo uri, sino carpeta sino manda peticion
        }

        location ~ \.php$ { #si el archivo termina el php
            fastcgi_pass wordpress:9000; #envia al servicio wordpress por ese puerto
            fastcgi_index index.php; #archivo por defecto
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; #archivo que debe cocinar wordpress
        }

        location ~ /\.ht {
            deny all; #si se intenta acceder a archivos htacess, prohibe acceso
        }
    }
}